# Creating a new appeal
POST  http://localhost:3000/appeal/ HTTP/1.1
Content-Type: application/json

{
  "client": "Мурашов Алексей Александрович",
  "email": "Alex@1984MA.com",
  "topicAppeal": "Замена паспорта.",
  "appeal": "Прошу поменять паспорт."
}
